// Code generated by MockGen. DO NOT EDIT.
// Source: ./chains/evm/listener/handlers/stateRoot.go
//
// Generated by this command:
//
//	mockgen -source=./chains/evm/listener/handlers/stateRoot.go -destination=./mock/stateRoot.go -package mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockEventFetcher is a mock of EventFetcher interface.
type MockEventFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventFetcherMockRecorder
}

// MockEventFetcherMockRecorder is the mock recorder for MockEventFetcher.
type MockEventFetcherMockRecorder struct {
	mock *MockEventFetcher
}

// NewMockEventFetcher creates a new mock instance.
func NewMockEventFetcher(ctrl *gomock.Controller) *MockEventFetcher {
	mock := &MockEventFetcher{ctrl: ctrl}
	mock.recorder = &MockEventFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventFetcher) EXPECT() *MockEventFetcherMockRecorder {
	return m.recorder
}

// FetchEventLogs mocks base method.
func (m *MockEventFetcher) FetchEventLogs(ctx context.Context, contractAddress common.Address, event string, startBlock, endBlock *big.Int) ([]types.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchEventLogs", ctx, contractAddress, event, startBlock, endBlock)
	ret0, _ := ret[0].([]types.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchEventLogs indicates an expected call of FetchEventLogs.
func (mr *MockEventFetcherMockRecorder) FetchEventLogs(ctx, contractAddress, event, startBlock, endBlock any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchEventLogs", reflect.TypeOf((*MockEventFetcher)(nil).FetchEventLogs), ctx, contractAddress, event, startBlock, endBlock)
}
