// Code generated by MockGen. DO NOT EDIT.
// Source: ./chains/evm/message/stateRoot.go
//
// Generated by this command:
//
//	mockgen -source=./chains/evm/message/stateRoot.go -destination=./mock/stateRootMessage.go -package mock
//
// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	api "github.com/attestantio/go-eth2-client/api"
	spec "github.com/attestantio/go-eth2-client/spec"
	gomock "go.uber.org/mock/gomock"
)

// MockBlockFetcher is a mock of BlockFetcher interface.
type MockBlockFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockBlockFetcherMockRecorder
}

// MockBlockFetcherMockRecorder is the mock recorder for MockBlockFetcher.
type MockBlockFetcherMockRecorder struct {
	mock *MockBlockFetcher
}

// NewMockBlockFetcher creates a new mock instance.
func NewMockBlockFetcher(ctrl *gomock.Controller) *MockBlockFetcher {
	mock := &MockBlockFetcher{ctrl: ctrl}
	mock.recorder = &MockBlockFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockFetcher) EXPECT() *MockBlockFetcherMockRecorder {
	return m.recorder
}

// SignedBeaconBlock mocks base method.
func (m *MockBlockFetcher) SignedBeaconBlock(ctx context.Context, opts *api.SignedBeaconBlockOpts) (*api.Response[*spec.VersionedSignedBeaconBlock], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignedBeaconBlock", ctx, opts)
	ret0, _ := ret[0].(*api.Response[*spec.VersionedSignedBeaconBlock])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignedBeaconBlock indicates an expected call of SignedBeaconBlock.
func (mr *MockBlockFetcherMockRecorder) SignedBeaconBlock(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignedBeaconBlock", reflect.TypeOf((*MockBlockFetcher)(nil).SignedBeaconBlock), ctx, opts)
}

// MockBlockStorer is a mock of BlockStorer interface.
type MockBlockStorer struct {
	ctrl     *gomock.Controller
	recorder *MockBlockStorerMockRecorder
}

// MockBlockStorerMockRecorder is the mock recorder for MockBlockStorer.
type MockBlockStorerMockRecorder struct {
	mock *MockBlockStorer
}

// NewMockBlockStorer creates a new mock instance.
func NewMockBlockStorer(ctrl *gomock.Controller) *MockBlockStorer {
	mock := &MockBlockStorer{ctrl: ctrl}
	mock.recorder = &MockBlockStorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockStorer) EXPECT() *MockBlockStorerMockRecorder {
	return m.recorder
}

// LatestBlock mocks base method.
func (m *MockBlockStorer) LatestBlock(sourceDomainID, destinationDomainID uint8) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LatestBlock", sourceDomainID, destinationDomainID)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LatestBlock indicates an expected call of LatestBlock.
func (mr *MockBlockStorerMockRecorder) LatestBlock(sourceDomainID, destinationDomainID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LatestBlock", reflect.TypeOf((*MockBlockStorer)(nil).LatestBlock), sourceDomainID, destinationDomainID)
}

// StoreBlock mocks base method.
func (m *MockBlockStorer) StoreBlock(sourceDomainID, destinationDomainID uint8, blockNumber *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreBlock", sourceDomainID, destinationDomainID, blockNumber)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreBlock indicates an expected call of StoreBlock.
func (mr *MockBlockStorerMockRecorder) StoreBlock(sourceDomainID, destinationDomainID, blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreBlock", reflect.TypeOf((*MockBlockStorer)(nil).StoreBlock), sourceDomainID, destinationDomainID, blockNumber)
}

// MockDepositHandler is a mock of DepositHandler interface.
type MockDepositHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDepositHandlerMockRecorder
}

// MockDepositHandlerMockRecorder is the mock recorder for MockDepositHandler.
type MockDepositHandlerMockRecorder struct {
	mock *MockDepositHandler
}

// NewMockDepositHandler creates a new mock instance.
func NewMockDepositHandler(ctrl *gomock.Controller) *MockDepositHandler {
	mock := &MockDepositHandler{ctrl: ctrl}
	mock.recorder = &MockDepositHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepositHandler) EXPECT() *MockDepositHandlerMockRecorder {
	return m.recorder
}

// HandleDeposits mocks base method.
func (m *MockDepositHandler) HandleDeposits(destination uint8, startBlock, endBlock, slot *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleDeposits", destination, startBlock, endBlock, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleDeposits indicates an expected call of HandleDeposits.
func (mr *MockDepositHandlerMockRecorder) HandleDeposits(destination, startBlock, endBlock, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleDeposits", reflect.TypeOf((*MockDepositHandler)(nil).HandleDeposits), destination, startBlock, endBlock, slot)
}

// MockHashiHandler is a mock of HashiHandler interface.
type MockHashiHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHashiHandlerMockRecorder
}

// MockHashiHandlerMockRecorder is the mock recorder for MockHashiHandler.
type MockHashiHandlerMockRecorder struct {
	mock *MockHashiHandler
}

// NewMockHashiHandler creates a new mock instance.
func NewMockHashiHandler(ctrl *gomock.Controller) *MockHashiHandler {
	mock := &MockHashiHandler{ctrl: ctrl}
	mock.recorder = &MockHashiHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashiHandler) EXPECT() *MockHashiHandlerMockRecorder {
	return m.recorder
}

// HandleMessages mocks base method.
func (m *MockHashiHandler) HandleMessages(destination uint8, startBlock, endBlock, slot *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessages", destination, startBlock, endBlock, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMessages indicates an expected call of HandleMessages.
func (mr *MockHashiHandlerMockRecorder) HandleMessages(destination, startBlock, endBlock, slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessages", reflect.TypeOf((*MockHashiHandler)(nil).HandleMessages), destination, startBlock, endBlock, slot)
}
